name: CI
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3.5.1

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install UV
        uses: astral-sh/setup-uv@v7.0.0
      - name: mypy
        run: uv run mypy --cache-dir=/dev/null dexi
